name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Heroku registry
        uses: docker/login-action@v2
        with:
          registry: registry.heroku.com
          username: ${{secrets.HEROKU_EMAIL}}
          password: ${{secrets.HEROKU_API_KEY}}

      - name: Build and publish
        run: |
          heroku container:push web -a ${{secrets.HEROKU_APP_NAME}}
          heroku container:release web -a ${{secrets.HEROKU_APP_NAME}}
